### ISSUE TITLE
fails to build with gfortran 4.9.1

### ISSUE THREAD

**Issue by davydden** [certik/dftatom#15]
configured with `cmake . -DWITH_C_INTERFACE=yes -DWITH_LAPACK=yes` 
finishes fine with

```
Configuration results
---------------------
Fortran compiler: /usr/local/bin/gfortran
Build type: Debug
Fortran compiler flags: -std=f2003 -Wall -Wextra -Wimplicit-interface -fPIC -Werror -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace
Installation prefix: /usr/local
With C interface: yes
With Python: no
With Lapack: yes
-- Configuring done
```

Yet, there are compilation errors:

```
[  1%] Building Fortran object src/CMakeFiles/dftatom.dir/ode1d.f90.o
/Users/davydden/Desktop/work/C++/dftatom/dftatom-1.0.2/src/ode1d.f90:107:0: error: 'integrate_adams' defined but not used [-Werror=unused-function]
 real(dp) function integrate_adams(Rp, f) result(s)
 ^
/Users/davydden/Desktop/work/C++/dftatom/dftatom-1.0.2/src/ode1d.f90:89:0: error: 'integrate_simpson' defined but not used [-Werror=unused-function]
 real(dp) function integrate_simpson(Rp, f) result(s)
 ^
/Users/davydden/Desktop/work/C++/dftatom/dftatom-1.0.2/src/ode1d.f90:55:0: error: 'integrate_trapz_5' defined but not used [-Werror=unused-function]
 real(dp) function integrate_trapz_5(Rp, f) result(s)
 ^
/Users/davydden/Desktop/work/C++/dftatom/dftatom-1.0.2/src/ode1d.f90:44:0: error: 'integrate_trapz_3' defined but not used [-Werror=unused-function]
 real(dp) function integrate_trapz_3(Rp, f) result(s)
 ^
f951: all warnings being treated as errors
```

p.s. 

```
gfortran --version
GNU Fortran (Homebrew gcc 4.9.1 --without-multilib) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
```
